@extends('adminlte::page')

@section('title', 'School Settings')

@section('content_header')
    <h1>School Settings</h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-info card-outline shadow-sm" style="border-radius: 10px;">
                    <form action="{{ route('settings.school.update') }}" method="POST">
                        @csrf
                        <div class="card-body">
                            @if(session('success'))
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                    {{ session('success') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif

                            <div class="form-group">
                                <label for="name">School Name</label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name" value="{{ old('name', $school->name) }}" required>
                                @error('name')
                                    <span class="invalid-feedback">{{ $message }}</span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="email">School Email</label>
                                <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" id="email" value="{{ old('email', $school->email) }}">
                                @error('email')
                                    <span class="invalid-feedback">{{ $message }}</span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="head_phone">Head Phone Number</label>
                                <input type="text" name="head_phone" class="form-control @error('head_phone') is-invalid @enderror" id="head_phone" value="{{ old('head_phone', $school->head_phone) }}">
                                @error('head_phone')
                                    <span class="invalid-feedback">{{ $message }}</span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="reg_number">School Registration Number</label>
                                <input type="text" name="reg_number" class="form-control @error('reg_number') is-invalid @enderror" id="reg_number" value="{{ old('reg_number', $school->reg_number) }}">
                                @error('reg_number')
                                    <span class="invalid-feedback">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="card-footer bg-white">
                            <button type="submit" class="btn btn-info px-4 shadow-sm" style="border-radius: 6px;">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card shadow-sm border-0" style="border-radius: 10px; background: #f8f9fa;">
                    <div class="card-body">
                        <h5><i class="fas fa-info-circle mr-2 text-info"></i> Active School Info</h5>
                        <p class="text-muted small">These details are used in report forms and official documents generated by the system.</p>
                        
                        <div class="mt-4">
                            <div class="mb-2"><strong>Current Active School:</strong></div>
                            <div class="h4 font-weight-bold text-dark">{{ $school->name }}</div>
                            <div class="text-muted">{{ $school->reg_number ?? 'No Registration Number' }}</div>
                        </div>

                        <div class="mt-4 pt-3 border-top">
                            <div class="small mb-1">Official Email:</div>
                            <div class="font-weight-bold">{{ $school->email ?? 'Not set' }}</div>
                        </div>

                        <div class="mt-2">
                            <div class="small mb-1">Official Contact:</div>
                            <div class="font-weight-bold">{{ $school->head_phone ?? 'Not set' }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
